### PR TITLE
Create notes

### PR DESCRIPTION
**Pull request by AliTaee**

### CODE REVIEW

**Comment by AliTaee** [comment]
[Create Page](https://trello.com/c/IhbluXfR/2-create-page)

**Comment by AliTaee** [comment]
> Why so many of eslint rules are disabled?

This is what you mean?
rules: {
    indent: 0,
    'no-tabs': 0,
    'eol-last': ['error', 'always'],
    'no-underscore-dangle': 0,
    'react/jsx-indent': 0,
    'react/jsx-indent-props': 0,
    'react/jsx-filename-extension': 0,
    'react/forbid-prop-types': 0,
    'react/require-default-props': 0,
  },

**Comment by AliTaee** [comment]
> Please fix the eslint errors.
> Prettier doesn't work.
> Use Material UI components as much as possible.
> Set up eslint to ignore EOL.
> Why so many of eslint rules are disabled?

Done.

**Comment by AliTaee** [comment]
> Use Material UI components as much as possible.
Replace unorder list with materail list item in View component

**Comment by sohrabtaee** [comment]
There is still one eslint error:
```
with-redux-store.js
  43:48  error  'initialReduxState' is missing in props validation  react/prop-types
```

- Create an npm script to run eslint on your project. E.g. `npm run lint`.
- There are two npm scripts `npm run dev` and `npm start`. What's the difference and usage of each? If they are the same, remove one of them.
- The UI for creating tasks is not consistent, the title input and description input have different UX.
- The validation error message should have a better UX according to material standards.
- After a note is created and the form is cleaned, the title input should be focuesd.

**Comment by AliTaee** [comment]
> * Create an npm script to run eslint on your project. E.g. `npm run lint`.
There is lint script in package.json
"scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "lint": "eslint pages/**/*.js pages/**/*.jsx components/**/*.jsx"
  },

**Comment by AliTaee** [comment]
npm run dev for start local development.
npm start for start build code

**Comment by sohrabtaee** [comment]
> npm run dev for start local development.
> npm start for start build code on local host

Then what is `npm run build`?

**Comment by AliTaee** [comment]
Then what is `npm run build`?
It is create build but npm start run build files on local host
and npm run dev for starting dev file's on local host.

**Comment by AliTaee** [comment]
> > npm run dev for start local development.
> > npm start for start build code on local host
> 
> Then what is `npm run build`?

It is create build but npm start run build files on local host
and npm run dev for starting dev file's on local host.

**Pull request merged**
